/**
 * 7 worship aid page templates with exact mm positions.
 * All geometry targets the half-letter page (177.8 x 215.9 mm).
 * Margins: top 15, bottom 15, inner 20, outer 12.
 * Live area: 145.8w x 185.9h, starting at (20, 15).
 */

import { PAGE_SIZES } from "@/types/schema";
import { FONT_FAMILIES, FONT_SIZES, FONT_WEIGHTS, LINE_HEIGHTS, LETTER_SPACING } from "@/core/design-system/tokens/typography";
import { MARGINS, SPACING, SEASON_BAR, COPYRIGHT_ZONE } from "@/core/design-system/tokens/spacing";
import type { TemplateDefinition } from "./schema";

const PAGE = PAGE_SIZES["half-letter"];
const LX = MARGINS.inner;                    // Live area left X (20mm)
const LW = PAGE.width - MARGINS.inner - MARGINS.outer; // Live area width (145.8mm)

// ── 1. Cover Page ──────────────────────────────────────────────────────────────

export const coverTemplate: TemplateDefinition = {
  id: "cover",
  label: "Cover",
  description: "Parish logo, occasion title, date, season accent bar",
  pageSize: PAGE,
  backgroundColor: "#FFFFFF",
  slots: [
    {
      id: "season-bar-top",
      label: "Season Bar (top)",
      elementType: "shape",
      required: false,
      geometry: { x: 0, y: 0, width: PAGE.width, height: SEASON_BAR.height },
      defaults: {
        type: "shape",
        subType: "rectangle",
        fill: "var(--wa-primary, #186420)",
        stroke: "transparent",
        strokeWidth: 0,
      },
    },
    {
      id: "logo",
      label: "Parish Logo",
      elementType: "image",
      required: false,
      geometry: { x: LX + 30, y: 30, width: 85, height: 50 },
      defaults: {
        type: "image",
        src: "",
        objectFit: "contain",
        cropTop: 0,
        cropLeft: 0,
        cropWidth: 1,
        cropHeight: 1,
        opacity: 1,
      },
    },
    {
      id: "parish-name",
      label: "Parish Name",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: 88, width: LW, height: 12 },
      defaults: {
        type: "text",
        content: "St. Monica Catholic Church",
        fontSize: FONT_SIZES.h3,
        fontFamily: FONT_FAMILIES.heading,
        fontWeight: FONT_WEIGHTS.semibold,
        color: "var(--wa-text-accent, #0E3B12)",
        textAlign: "center",
        lineHeight: LINE_HEIGHTS.relaxed,
        letterSpacing: LETTER_SPACING.wide,
        textTransform: "uppercase",
      },
    },
    {
      id: "occasion-title",
      label: "Occasion Title",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: 110, width: LW, height: 20 },
      defaults: {
        type: "text",
        content: "Sunday Liturgy",
        fontSize: FONT_SIZES.h1,
        fontFamily: FONT_FAMILIES.body,
        fontWeight: FONT_WEIGHTS.regular,
        color: "#1A1A1A",
        textAlign: "center",
        lineHeight: LINE_HEIGHTS.tight,
        letterSpacing: LETTER_SPACING.tight,
      },
    },
    {
      id: "date",
      label: "Date",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: 135, width: LW, height: 8 },
      defaults: {
        type: "text",
        content: "",
        fontSize: FONT_SIZES.body,
        fontFamily: FONT_FAMILIES.heading,
        fontWeight: FONT_WEIGHTS.light,
        color: "#57534E",
        textAlign: "center",
        lineHeight: LINE_HEIGHTS.normal,
        letterSpacing: LETTER_SPACING.wide,
      },
    },
    {
      id: "season-bar-bottom",
      label: "Season Bar (bottom)",
      elementType: "shape",
      required: false,
      geometry: { x: 0, y: PAGE.height - SEASON_BAR.height, width: PAGE.width, height: SEASON_BAR.height },
      defaults: {
        type: "shape",
        subType: "rectangle",
        fill: "var(--wa-primary, #186420)",
        stroke: "transparent",
        strokeWidth: 0,
      },
    },
  ],
};

// ── 2. Song Reprint ────────────────────────────────────────────────────────────

export const songReprintTemplate: TemplateDefinition = {
  id: "song-reprint",
  label: "Song Reprint",
  description: "Song header + full-width reprint image + copyright footer",
  pageSize: PAGE,
  backgroundColor: "#FFFFFF",
  slots: [
    {
      id: "song-title",
      label: "Song Title",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: MARGINS.top, width: LW, height: 12 },
      defaults: {
        type: "text",
        content: "Song Title",
        fontSize: 17,
        fontFamily: FONT_FAMILIES.body,
        fontWeight: FONT_WEIGHTS.regular,
        color: "var(--wa-text-accent, #1A1A1A)",
        textAlign: "left",
        lineHeight: LINE_HEIGHTS.tight,
        letterSpacing: LETTER_SPACING.wide,
        textTransform: "small-caps",
      },
    },
    {
      id: "composer",
      label: "Composer/Author",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: MARGINS.top + 13, width: LW, height: 5 },
      defaults: {
        type: "text",
        content: "",
        fontSize: 10.5,
        fontFamily: FONT_FAMILIES.body,
        fontWeight: FONT_WEIGHTS.regular,
        color: "#57534E",
        textAlign: "left",
        lineHeight: LINE_HEIGHTS.normal,
        letterSpacing: LETTER_SPACING.normal,
      },
    },
    {
      id: "position-label",
      label: "Position (Gathering, Communion, etc.)",
      elementType: "text",
      required: false,
      geometry: { x: LX, y: MARGINS.top + 19, width: LW, height: 4 },
      defaults: {
        type: "text",
        content: "",
        fontSize: 7.5,
        fontFamily: FONT_FAMILIES.heading,
        fontWeight: FONT_WEIGHTS.regular,
        color: "#8C8581",
        textAlign: "left",
        lineHeight: LINE_HEIGHTS.tight,
        letterSpacing: LETTER_SPACING.extraWide,
        textTransform: "uppercase",
      },
    },
    {
      id: "divider-top",
      label: "Divider",
      elementType: "divider",
      required: false,
      geometry: { x: LX, y: MARGINS.top + 22, width: LW, height: 0 },
      defaults: {
        type: "divider",
        stroke: "var(--wa-border, #E7E5E4)",
        strokeWidth: 0.3,
        strokeStyle: "solid",
      },
    },
    {
      id: "reprint-image",
      label: "Sheet Music Reprint",
      elementType: "image",
      required: false,
      geometry: { x: LX, y: MARGINS.top + 25, width: LW, height: 152 },
      defaults: {
        type: "image",
        src: "",
        objectFit: "contain",
        cropTop: 0,
        cropLeft: 0,
        cropWidth: 1,
        cropHeight: 1,
        opacity: 1,
      },
    },
    {
      id: "copyright",
      label: "Copyright",
      elementType: "text",
      required: true,
      placeholder: "Copyright notice required by reprint license",
      geometry: { x: LX, y: COPYRIGHT_ZONE.y, width: LW, height: COPYRIGHT_ZONE.height },
      defaults: {
        type: "text",
        content: "",
        fontSize: FONT_SIZES.copyright,
        fontFamily: FONT_FAMILIES.body,
        fontWeight: FONT_WEIGHTS.regular,
        color: "#78716C",
        textAlign: "left",
        lineHeight: LINE_HEIGHTS.tight,
        letterSpacing: LETTER_SPACING.normal,
      },
    },
  ],
};

// ── 3. Two-Up Songs ────────────────────────────────────────────────────────────

const halfW = (LW - SPACING.md) / 2; // Two columns with gap

export const twoUpSongsTemplate: TemplateDefinition = {
  id: "two-up-songs",
  label: "Two-Up Songs",
  description: "Two song reprints side by side on one page",
  pageSize: PAGE,
  backgroundColor: "#FFFFFF",
  slots: [
    {
      id: "left-title",
      label: "Left Song Title",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: MARGINS.top, width: halfW, height: 8 },
      defaults: {
        type: "text",
        content: "Song A",
        fontSize: FONT_SIZES.h4,
        fontFamily: FONT_FAMILIES.heading,
        fontWeight: FONT_WEIGHTS.semibold,
        color: "var(--wa-text-accent, #1A1A1A)",
        textAlign: "left",
        lineHeight: LINE_HEIGHTS.tight,
        letterSpacing: LETTER_SPACING.normal,
      },
    },
    {
      id: "left-image",
      label: "Left Reprint",
      elementType: "image",
      required: false,
      geometry: { x: LX, y: MARGINS.top + 10, width: halfW, height: 160 },
      defaults: {
        type: "image",
        src: "",
        objectFit: "contain",
        cropTop: 0,
        cropLeft: 0,
        cropWidth: 1,
        cropHeight: 1,
        opacity: 1,
      },
    },
    {
      id: "right-title",
      label: "Right Song Title",
      elementType: "text",
      required: true,
      geometry: { x: LX + halfW + SPACING.md, y: MARGINS.top, width: halfW, height: 8 },
      defaults: {
        type: "text",
        content: "Song B",
        fontSize: FONT_SIZES.h4,
        fontFamily: FONT_FAMILIES.heading,
        fontWeight: FONT_WEIGHTS.semibold,
        color: "var(--wa-text-accent, #1A1A1A)",
        textAlign: "left",
        lineHeight: LINE_HEIGHTS.tight,
        letterSpacing: LETTER_SPACING.normal,
      },
    },
    {
      id: "right-image",
      label: "Right Reprint",
      elementType: "image",
      required: false,
      geometry: { x: LX + halfW + SPACING.md, y: MARGINS.top + 10, width: halfW, height: 160 },
      defaults: {
        type: "image",
        src: "",
        objectFit: "contain",
        cropTop: 0,
        cropLeft: 0,
        cropWidth: 1,
        cropHeight: 1,
        opacity: 1,
      },
    },
    {
      id: "copyright",
      label: "Copyright (both)",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: COPYRIGHT_ZONE.y, width: LW, height: COPYRIGHT_ZONE.height },
      defaults: {
        type: "text",
        content: "",
        fontSize: FONT_SIZES.copyright,
        fontFamily: FONT_FAMILIES.body,
        fontWeight: FONT_WEIGHTS.regular,
        color: "#78716C",
        textAlign: "left",
        lineHeight: LINE_HEIGHTS.tight,
        letterSpacing: LETTER_SPACING.normal,
      },
    },
  ],
};

// ── 4. Readings ────────────────────────────────────────────────────────────────

export const readingsTemplate: TemplateDefinition = {
  id: "readings",
  label: "Readings",
  description: "First Reading, Responsorial Psalm, Second Reading, Gospel citations",
  pageSize: PAGE,
  backgroundColor: "#FFFFFF",
  slots: [
    {
      id: "header",
      label: "Liturgy of the Word",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: MARGINS.top, width: LW, height: 10 },
      defaults: {
        type: "text",
        content: "Liturgy of the Word",
        fontSize: FONT_SIZES.h2,
        fontFamily: FONT_FAMILIES.heading,
        fontWeight: FONT_WEIGHTS.semibold,
        color: "var(--wa-text-accent, #1A1A1A)",
        textAlign: "center",
        lineHeight: LINE_HEIGHTS.relaxed,
        letterSpacing: LETTER_SPACING.wide,
        textTransform: "uppercase",
      },
    },
    {
      id: "divider-header",
      label: "Header Divider",
      elementType: "divider",
      required: false,
      geometry: { x: LX + 30, y: MARGINS.top + 13, width: LW - 60, height: 0 },
      defaults: {
        type: "divider",
        stroke: "var(--wa-primary, #186420)",
        strokeWidth: 0.4,
        strokeStyle: "solid",
      },
    },
    {
      id: "first-reading",
      label: "First Reading",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: MARGINS.top + 20, width: LW, height: 35 },
      defaults: {
        type: "text",
        content: "<strong style=\"font-size:12pt\">First Reading</strong>",
        fontSize: FONT_SIZES.body,
        fontFamily: FONT_FAMILIES.body,
        fontWeight: FONT_WEIGHTS.regular,
        color: "#1A1A1A",
        textAlign: "left",
        lineHeight: LINE_HEIGHTS.normal,
        letterSpacing: LETTER_SPACING.normal,
      },
    },
    {
      id: "psalm",
      label: "Responsorial Psalm",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: MARGINS.top + 62, width: LW, height: 35 },
      defaults: {
        type: "text",
        content: "<strong style=\"font-size:12pt\">Responsorial Psalm</strong><br/><em><strong>R. Refrain text here</strong></em>",
        fontSize: FONT_SIZES.body,
        fontFamily: FONT_FAMILIES.body,
        fontWeight: FONT_WEIGHTS.regular,
        color: "#1A1A1A",
        textAlign: "left",
        lineHeight: LINE_HEIGHTS.normal,
        letterSpacing: LETTER_SPACING.normal,
      },
    },
    {
      id: "second-reading",
      label: "Second Reading",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: MARGINS.top + 104, width: LW, height: 35 },
      defaults: {
        type: "text",
        content: "<strong style=\"font-size:12pt\">Second Reading</strong>",
        fontSize: FONT_SIZES.body,
        fontFamily: FONT_FAMILIES.body,
        fontWeight: FONT_WEIGHTS.regular,
        color: "#1A1A1A",
        textAlign: "left",
        lineHeight: LINE_HEIGHTS.normal,
        letterSpacing: LETTER_SPACING.normal,
      },
    },
    {
      id: "gospel",
      label: "Gospel",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: MARGINS.top + 146, width: LW, height: 35 },
      defaults: {
        type: "text",
        content: "<strong style=\"font-size:12pt\">Gospel</strong>",
        fontSize: FONT_SIZES.body,
        fontFamily: FONT_FAMILIES.body,
        fontWeight: FONT_WEIGHTS.regular,
        color: "#1A1A1A",
        textAlign: "left",
        lineHeight: LINE_HEIGHTS.normal,
        letterSpacing: LETTER_SPACING.normal,
      },
    },
  ],
};

// ── 5. Compound Liturgy of the Word ────────────────────────────────────────────

export const compoundWordTemplate: TemplateDefinition = {
  id: "compound-word",
  label: "Compound Liturgy",
  description: "Readings + psalm + Gospel Acclamation on one page (compact)",
  pageSize: PAGE,
  backgroundColor: "#FFFFFF",
  slots: [
    {
      id: "header",
      label: "Section Header",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: MARGINS.top, width: LW, height: 8 },
      defaults: {
        type: "text",
        content: "Liturgy of the Word",
        fontSize: FONT_SIZES.h3,
        fontFamily: FONT_FAMILIES.heading,
        fontWeight: FONT_WEIGHTS.semibold,
        color: "var(--wa-text-accent, #1A1A1A)",
        textAlign: "center",
        lineHeight: LINE_HEIGHTS.tight,
        letterSpacing: LETTER_SPACING.wide,
        textTransform: "uppercase",
      },
    },
    {
      id: "first-reading",
      label: "First Reading",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: MARGINS.top + 12, width: LW, height: 28 },
      defaults: {
        type: "text",
        content: "<strong>First Reading</strong>",
        fontSize: 9,
        fontFamily: FONT_FAMILIES.body,
        fontWeight: FONT_WEIGHTS.regular,
        color: "#1A1A1A",
        textAlign: "left",
        lineHeight: LINE_HEIGHTS.tight,
        letterSpacing: LETTER_SPACING.normal,
      },
    },
    {
      id: "psalm",
      label: "Responsorial Psalm",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: MARGINS.top + 44, width: LW, height: 28 },
      defaults: {
        type: "text",
        content: "<strong>Responsorial Psalm</strong>",
        fontSize: 9,
        fontFamily: FONT_FAMILIES.body,
        fontWeight: FONT_WEIGHTS.regular,
        color: "#1A1A1A",
        textAlign: "left",
        lineHeight: LINE_HEIGHTS.tight,
        letterSpacing: LETTER_SPACING.normal,
      },
    },
    {
      id: "second-reading",
      label: "Second Reading",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: MARGINS.top + 76, width: LW, height: 28 },
      defaults: {
        type: "text",
        content: "<strong>Second Reading</strong>",
        fontSize: 9,
        fontFamily: FONT_FAMILIES.body,
        fontWeight: FONT_WEIGHTS.regular,
        color: "#1A1A1A",
        textAlign: "left",
        lineHeight: LINE_HEIGHTS.tight,
        letterSpacing: LETTER_SPACING.normal,
      },
    },
    {
      id: "gospel-acclamation",
      label: "Gospel Acclamation",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: MARGINS.top + 108, width: LW, height: 20 },
      defaults: {
        type: "text",
        content: "<strong>Gospel Acclamation</strong>",
        fontSize: 9,
        fontFamily: FONT_FAMILIES.body,
        fontWeight: FONT_WEIGHTS.regular,
        color: "#1A1A1A",
        textAlign: "left",
        lineHeight: LINE_HEIGHTS.tight,
        letterSpacing: LETTER_SPACING.normal,
      },
    },
    {
      id: "gospel",
      label: "Gospel",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: MARGINS.top + 132, width: LW, height: 50 },
      defaults: {
        type: "text",
        content: "<strong>Gospel</strong>",
        fontSize: 9,
        fontFamily: FONT_FAMILIES.body,
        fontWeight: FONT_WEIGHTS.regular,
        color: "#1A1A1A",
        textAlign: "left",
        lineHeight: LINE_HEIGHTS.tight,
        letterSpacing: LETTER_SPACING.normal,
      },
    },
  ],
};

// ── 6. Announcements ───────────────────────────────────────────────────────────

export const announcementsTemplate: TemplateDefinition = {
  id: "announcements",
  label: "Announcements",
  description: "Text blocks, QR code, parish info",
  pageSize: PAGE,
  backgroundColor: "#FFFFFF",
  slots: [
    {
      id: "header",
      label: "Announcements Header",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: MARGINS.top, width: LW, height: 10 },
      defaults: {
        type: "text",
        content: "Parish Announcements",
        fontSize: FONT_SIZES.h2,
        fontFamily: FONT_FAMILIES.heading,
        fontWeight: FONT_WEIGHTS.semibold,
        color: "var(--wa-text-accent, #1A1A1A)",
        textAlign: "center",
        lineHeight: LINE_HEIGHTS.relaxed,
        letterSpacing: LETTER_SPACING.wide,
        textTransform: "uppercase",
      },
    },
    {
      id: "divider",
      label: "Divider",
      elementType: "divider",
      required: false,
      geometry: { x: LX + 30, y: MARGINS.top + 13, width: LW - 60, height: 0 },
      defaults: {
        type: "divider",
        stroke: "var(--wa-primary, #186420)",
        strokeWidth: 0.4,
        strokeStyle: "solid",
      },
    },
    {
      id: "announcement-1",
      label: "Announcement Block 1",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: MARGINS.top + 20, width: LW, height: 40 },
      defaults: {
        type: "text",
        content: "",
        fontSize: FONT_SIZES.body,
        fontFamily: FONT_FAMILIES.body,
        fontWeight: FONT_WEIGHTS.regular,
        color: "#1A1A1A",
        textAlign: "left",
        lineHeight: LINE_HEIGHTS.normal,
        letterSpacing: LETTER_SPACING.normal,
      },
    },
    {
      id: "announcement-2",
      label: "Announcement Block 2",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: MARGINS.top + 68, width: LW, height: 40 },
      defaults: {
        type: "text",
        content: "",
        fontSize: FONT_SIZES.body,
        fontFamily: FONT_FAMILIES.body,
        fontWeight: FONT_WEIGHTS.regular,
        color: "#1A1A1A",
        textAlign: "left",
        lineHeight: LINE_HEIGHTS.normal,
        letterSpacing: LETTER_SPACING.normal,
      },
    },
    {
      id: "qr-code",
      label: "QR Code",
      elementType: "qr",
      required: false,
      geometry: { x: LX + LW - 35, y: MARGINS.top + 120, width: 35, height: 35 },
      defaults: {
        type: "qr",
        url: "https://stmonica.net",
        foregroundColor: "#1A1A1A",
        backgroundColor: "#FFFFFF",
      },
    },
    {
      id: "qr-label",
      label: "QR Label",
      elementType: "text",
      required: true,
      geometry: { x: LX + LW - 45, y: MARGINS.top + 157, width: 45, height: 6 },
      defaults: {
        type: "text",
        content: "stmonica.net",
        fontSize: FONT_SIZES.caption,
        fontFamily: FONT_FAMILIES.heading,
        fontWeight: FONT_WEIGHTS.regular,
        color: "#57534E",
        textAlign: "center",
        lineHeight: LINE_HEIGHTS.normal,
        letterSpacing: LETTER_SPACING.normal,
      },
    },
  ],
};

// ── 7. Back Cover ──────────────────────────────────────────────────────────────

export const backCoverTemplate: TemplateDefinition = {
  id: "back-cover",
  label: "Back Cover",
  description: "Contact info, Mass schedule, parish branding",
  pageSize: PAGE,
  backgroundColor: "#FFFFFF",
  slots: [
    {
      id: "season-bar-top",
      label: "Season Bar",
      elementType: "shape",
      required: false,
      geometry: { x: 0, y: 0, width: PAGE.width, height: SEASON_BAR.height },
      defaults: {
        type: "shape",
        subType: "rectangle",
        fill: "var(--wa-primary, #186420)",
        stroke: "transparent",
        strokeWidth: 0,
      },
    },
    {
      id: "parish-name",
      label: "Parish Name",
      elementType: "text",
      required: true,
      geometry: { x: LX, y: 25, width: LW, height: 12 },
      defaults: {
        type: "text",
        content: "St. Monica Catholic Church",
        fontSize: FONT_SIZES.h3,
        fontFamily: FONT_FAMILIES.heading,
        fontWeight: FONT_WEIGHTS.semibold,
        color: "var(--wa-text-accent, #1A1A1A)",
        textAlign: "center",
        lineHeight: LINE_HEIGHTS.relaxed,
        letterSpacing: LETTER_SPACING.wide,
        textTransform: "uppercase",
      },
    },
    {
      id: "mass-schedule",
      label: "Mass Schedule",
      elementType: "text",
      required: true,
      geometry: { x: LX + 15, y: 50, width: LW - 30, height: 60 },
      defaults: {
        type: "text",
        content: "<strong>Mass Schedule</strong>",
        fontSize: FONT_SIZES.body,
        fontFamily: FONT_FAMILIES.body,
        fontWeight: FONT_WEIGHTS.regular,
        color: "#1A1A1A",
        textAlign: "center",
        lineHeight: LINE_HEIGHTS.normal,
        letterSpacing: LETTER_SPACING.normal,
      },
    },
    {
      id: "contact",
      label: "Contact Info",
      elementType: "text",
      required: true,
      geometry: { x: LX + 15, y: 120, width: LW - 30, height: 40 },
      defaults: {
        type: "text",
        content: "",
        fontSize: FONT_SIZES.body,
        fontFamily: FONT_FAMILIES.body,
        fontWeight: FONT_WEIGHTS.regular,
        color: "#57534E",
        textAlign: "center",
        lineHeight: LINE_HEIGHTS.normal,
        letterSpacing: LETTER_SPACING.normal,
      },
    },
    {
      id: "website-qr",
      label: "Website QR",
      elementType: "qr",
      required: false,
      geometry: { x: LX + (LW - 30) / 2, y: 168, width: 30, height: 30 },
      defaults: {
        type: "qr",
        url: "https://stmonica.net",
        foregroundColor: "#1A1A1A",
        backgroundColor: "#FFFFFF",
      },
    },
    {
      id: "season-bar-bottom",
      label: "Season Bar",
      elementType: "shape",
      required: false,
      geometry: { x: 0, y: PAGE.height - SEASON_BAR.height, width: PAGE.width, height: SEASON_BAR.height },
      defaults: {
        type: "shape",
        subType: "rectangle",
        fill: "var(--wa-primary, #186420)",
        stroke: "transparent",
        strokeWidth: 0,
      },
    },
  ],
};

// ── All templates ──────────────────────────────────────────────────────────────

export const ALL_TEMPLATES: TemplateDefinition[] = [
  coverTemplate,
  songReprintTemplate,
  twoUpSongsTemplate,
  readingsTemplate,
  compoundWordTemplate,
  announcementsTemplate,
  backCoverTemplate,
];
