-- ============================================================
-- Migration 016: Volunteer Signup System
-- ============================================================
-- Adds:
--   1. profiles — status, sms_consent columns
--   2. invitations table — invite-code system for new users
--   3. notifications_log table — outbound SMS/email audit trail
--   4. is_active_user() helper function
--   5. RLS policies for new tables
--   6. Updated SELECT policies on mass_events, booking_slots,
--      choir_signups to block pending users
-- Idempotent: uses IF NOT EXISTS and DO $$ blocks throughout.
-- ============================================================

-- ============================================================
-- 1. EXTEND profiles: status + SMS consent fields
-- ============================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'status'
  ) THEN
    ALTER TABLE public.profiles
      ADD COLUMN status text NOT NULL DEFAULT 'active'
      CHECK (status IN ('pending', 'active', 'inactive'));
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'sms_consent'
  ) THEN
    ALTER TABLE public.profiles ADD COLUMN sms_consent boolean DEFAULT false;
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'sms_consent_at'
  ) THEN
    ALTER TABLE public.profiles ADD COLUMN sms_consent_at timestamptz;
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'sms_consent_method'
  ) THEN
    -- Values: 'text_to_join', 'signup_form', 'admin_import'
    ALTER TABLE public.profiles ADD COLUMN sms_consent_method text;
  END IF;
END $$;
-- ============================================================
-- 2. HELPER FUNCTION: is_active_user
-- ============================================================
-- Returns true if the given uid maps to a profile with
-- status = 'active'. Used in RLS policies below.
-- SECURITY DEFINER: runs as the function owner, so it can
-- read profiles regardless of caller's RLS context.

CREATE OR REPLACE FUNCTION public.is_active_user(uid uuid)
RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles WHERE id = uid AND status = 'active'
  );
$$ LANGUAGE sql SECURITY DEFINER STABLE;
-- ============================================================
-- 3. INVITATIONS TABLE
-- ============================================================
-- Admin-issued invite codes. A new volunteer redeems a code
-- during signup to get a pre-approved account.

CREATE TABLE IF NOT EXISTS public.invitations (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  code        text        UNIQUE NOT NULL,          -- 8-char alphanumeric (generated by app)
  invited_by  uuid        REFERENCES public.profiles(id) ON DELETE SET NULL,
  invited_phone text,                               -- if delivered via SMS
  invited_email text,                               -- if delivered via email
  ensemble    text,                                 -- pre-fill ensemble on signup form
  status      text        NOT NULL DEFAULT 'pending'
              CHECK (status IN ('pending', 'claimed', 'expired')),
  claimed_by  uuid        REFERENCES public.profiles(id) ON DELETE SET NULL,
  claimed_at  timestamptz,
  expires_at  timestamptz NOT NULL DEFAULT (now() + interval '30 days'),
  created_at  timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.invitations ENABLE ROW LEVEL SECURITY;
-- Admins can view all invitations
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'invitations' AND policyname = 'Admins can view invitations'
  ) THEN
    CREATE POLICY "Admins can view invitations"
      ON public.invitations FOR SELECT
      USING (
        EXISTS (
          SELECT 1 FROM public.profiles
          WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
        )
      );
  END IF;
END $$;
-- Admins can create invitations
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'invitations' AND policyname = 'Admins can insert invitations'
  ) THEN
    CREATE POLICY "Admins can insert invitations"
      ON public.invitations FOR INSERT
      WITH CHECK (
        EXISTS (
          SELECT 1 FROM public.profiles
          WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
        )
      );
  END IF;
END $$;
-- Admins can update any invitation; claiming user can update their own claimed row
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'invitations' AND policyname = 'Admins and claimants can update invitations'
  ) THEN
    CREATE POLICY "Admins and claimants can update invitations"
      ON public.invitations FOR UPDATE
      USING (
        EXISTS (
          SELECT 1 FROM public.profiles
          WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
        )
        OR auth.uid() = claimed_by
      );
  END IF;
END $$;
-- Index: look up by code (claim flow) and by invited_by (admin dashboard)
CREATE INDEX IF NOT EXISTS idx_invitations_code ON public.invitations(code);
CREATE INDEX IF NOT EXISTS idx_invitations_invited_by ON public.invitations(invited_by);
CREATE INDEX IF NOT EXISTS idx_invitations_status ON public.invitations(status);
-- ============================================================
-- 4. NOTIFICATIONS_LOG TABLE
-- ============================================================
-- Audit trail for every outbound SMS (Twilio) and email (Resend)
-- the system sends. Never written by end users — only service role.

CREATE TABLE IF NOT EXISTS public.notifications_log (
  id            uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
  recipient_id  uuid    REFERENCES public.profiles(id) ON DELETE SET NULL,
  channel       text    NOT NULL CHECK (channel IN ('sms', 'email')),
  message_type  text    NOT NULL,
  -- message_type values: 'welcome', 'approved', 'reminder', 'announcement', 'invite'
  external_id   text,   -- Twilio MessageSID or Resend email ID
  status        text    NOT NULL DEFAULT 'sent',
  created_at    timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.notifications_log ENABLE ROW LEVEL SECURITY;
-- Admins can read the log
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'notifications_log' AND policyname = 'Admins can view notifications log'
  ) THEN
    CREATE POLICY "Admins can view notifications log"
      ON public.notifications_log FOR SELECT
      USING (
        EXISTS (
          SELECT 1 FROM public.profiles
          WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
        )
      );
  END IF;
END $$;
-- No INSERT policy for authenticated users: all writes go through
-- server-side code using the service role key (bypasses RLS).
-- A policy is intentionally omitted here to enforce that constraint.

-- Index: look up by recipient (notification history per user)
CREATE INDEX IF NOT EXISTS idx_notifications_log_recipient ON public.notifications_log(recipient_id);
CREATE INDEX IF NOT EXISTS idx_notifications_log_channel ON public.notifications_log(channel);
-- ============================================================
-- 5. UPDATE EXISTING SELECT POLICIES TO BLOCK PENDING USERS
-- ============================================================
-- Pending users can authenticate but should not see scheduling
-- data (mass_events, booking_slots, choir_signups) until approved.
-- Strategy: drop the broad "authenticated" SELECT policy and replace
-- it with one that requires is_active_user() OR admin role.
-- Admin check is explicit so that pending admins (rare edge case)
-- still get access.

-- Helper: admin check subquery used repeatedly below
-- (inline — no separate function needed)

-- ---- mass_events ----
DROP POLICY IF EXISTS "Anyone authenticated can view mass events" ON public.mass_events;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'mass_events' AND policyname = 'Active users can view mass events'
  ) THEN
    CREATE POLICY "Active users can view mass events"
      ON public.mass_events FOR SELECT
      USING (
        public.is_active_user(auth.uid())
        OR EXISTS (
          SELECT 1 FROM public.profiles
          WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
        )
      );
  END IF;
END $$;
-- ---- booking_slots ----
DROP POLICY IF EXISTS "Anyone authenticated can view booking slots" ON public.booking_slots;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'booking_slots' AND policyname = 'Active users can view booking slots'
  ) THEN
    CREATE POLICY "Active users can view booking slots"
      ON public.booking_slots FOR SELECT
      USING (
        public.is_active_user(auth.uid())
        OR EXISTS (
          SELECT 1 FROM public.profiles
          WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
        )
      );
  END IF;
END $$;
-- ---- choir_signups ----
DROP POLICY IF EXISTS "Anyone authenticated can view choir signups" ON public.choir_signups;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'choir_signups' AND policyname = 'Active users can view choir signups'
  ) THEN
    CREATE POLICY "Active users can view choir signups"
      ON public.choir_signups FOR SELECT
      USING (
        public.is_active_user(auth.uid())
        OR EXISTS (
          SELECT 1 FROM public.profiles
          WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
        )
      );
  END IF;
END $$;
-- ============================================================
-- NOTE: Pending user access model
-- ============================================================
-- Pending users are blocked primarily at the middleware/app layer
-- (Next.js middleware checks profile.status and redirects to a
-- "pending approval" page). RLS here provides defense-in-depth
-- for scheduling tables specifically.
--
-- Profiles SELECT policy intentionally left unchanged: pending
-- users may eventually need to see the members directory, and
-- the app layer controls what UI they reach. If stricter profile
-- isolation is needed, add is_active_user() to that policy too.
-- ============================================================;
